
const GalleryData = [
  {
    image: "product1 (1).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "gray-plastic-chair",
    price: "$19.00",
    defaultValue: "2.5",
  },
  {
    image: "product1 (2).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "black-wooden-chair",
    price: "$19.00",
    defaultValue: "3.5",
  },
  {
    image: "product1 (3).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "white-wooden-chair",
    price: "$19.00",
    defaultValue: "5",
  },
  {
    image: "product1 (4).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "woody-chair",
    price: "$19.00",
    defaultValue: "4.5",
  },
  {
    image: "product1 (5).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "black-seat-metall-base",
    price: "$19.00",
    defaultValue: "2.5",
  },
  {
    image: "product1 (6).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "single-sofa",
    price: "$19.00",
    defaultValue: "3.5",
  },
  {
    image: "product1 (7).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "seats-and-cabinets",
    price: "$19.00",
    defaultValue: "0.5",
  },
  {
    image: "prud3.jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "all-wood-seat",
    price: "$19.00",
    defaultValue: "1",
  },
  {
    image: "product1 (9).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "colored-plastic-chair",
    price: "$19.00",
    defaultValue: "2.5",
  },
  {
    image: "product1 (10).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "desk-and-chair",
    price: "$19.00",
    defaultValue: "2",
  },
  {
    image: "product1 (11).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "office-table-and-chair",
    price: "$19.00",
    defaultValue: "1",
  },
  {
    image: "product1 (12).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "metal-chair-with-wooden-handle",
    price: "$19.00",
    defaultValue: "4.5",
  },
  {
    image: "product1 (13).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "plastic-cumin-chair",
    price: "$19.00",
    defaultValue: "5",
  },
  {
    image: "product1 (14).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "footstool",
    price: "$19.00",
    defaultValue: "2.5",
  },
  {
    image: "product1 (15).jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "waiting-chair",
    price: "$19.00",
    defaultValue: "4.5",
  },
  {
    image: "prud1.jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "modern-seat",
    price: "$19.00",
    defaultValue: "4",
  },
  {
    image: "prud2.jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "modern-stool",
    price: "$19.00",
    defaultValue: "2.5",
  },
  {
    image: "prud4.jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "wood",
    price: "$19.00",
    defaultValue: "3.5",
  },
  {
    image: "prud5.jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "bar-seat",
    price: "$19.00",
    defaultValue: "0.5",
  },
  {
    image: "prud6.jpg",
    discriotion: "Eco plastic chair with armrests",
    id: "bar-seat-with-back",
    price: "$19.00",
    defaultValue: "1.5",
  },
];
export default GalleryData